### ISSUE TITLE
Too many runs from one PR, not sure why

### ISSUE THREAD

**Issue by pllim** [scientific-python/circleci-artifacts-redirector-action#59]
I have https://github.com/astropy/astropy.github.com/pull/619 with only 1 commit (at the time of writing). And I have https://github.com/astropy/astropy.github.com/blob/main/.github/workflows/circle_artifacts.yml using your Action. I noticed that this one commit triggered 4 builds, which was surprising to me:

<img src="https://github.com/user-attachments/assets/9353a86d-5d50-4a04-83b7-a555e6814395" width="600"/>

As a result, the builds now look "stuck" and there is no preview on my PR.

Do I have to tweak the workflow? Hope you can advise. Thanks!

**Comment by pllim** [comment]
Is this a duplicate of https://github.com/scientific-python/circleci-artifacts-redirector-action/issues/27 ? 🤔

**Comment by larsoner** [comment]
Yeah I think it is

**Comment by pllim** [comment]
With GitHub status green again, the preview works but I still see 4 builds per push. 🤷‍♀️  At least I have a preview now.
